import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';

@Injectable()
export class ExtraQuestionsService {

  constructor(public http: HttpClient) {}

  updateUser(data): Observable<any> {
    return this.http.put(`http://bl-members-dev.yelpix.work/members/wp-json/wp/v2/users/${data.user_id}`, data)
      .catch(err =>  Observable.throw(err.json() || 'Server error'))
  }

  getLocation(){
    return [
        { "type": "Feature", "properties": { "SNo": 1, "DE": "Abchasien", "EN": "Abkhazia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 2, "DE": "Afghanistan", "EN": "Afghanistan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 3, "DE": "Ägypten", "EN": "Egypt" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 4, "DE": "Albanien", "EN": "Albania" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 5, "DE": "Algerien", "EN": "Algeria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 6, "DE": "Andorra", "EN": "Andorra" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 7, "DE": "Angola", "EN": "Angola" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 8, "DE": "Antigua und Barbuda", "EN": "Antigua and Barbuda" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 9, "DE": "Äquatorialguinea", "EN": "Equatorial Guinea" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 10, "DE": "Argentinien", "EN": "Argentina" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 11, "DE": "Armenien", "EN": "Armenia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 12, "DE": "Aserbaidschan", "EN": "Azerbaijan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 13, "DE": "Äthiopien", "EN": "Ethiopia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 14, "DE": "Australien", "EN": "Australia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 15, "DE": "Bahamas", "EN": "Bahamas" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 16, "DE": "Bahrain", "EN": "Bahrain" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 17, "DE": "Bangladesch", "EN": "Bangladesh" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 18, "DE": "Barbados", "EN": "Barbados" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 19, "DE": "Belgien", "EN": "Belgium" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 20, "DE": "Belize", "EN": "Belize" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 21, "DE": "Benin", "EN": "Benin" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 22, "DE": "Bergkarabach", "EN": "Nagorno-Karabakh Republic" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 23, "DE": "Bhutan", "EN": "Bhutan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 24, "DE": "Bolivien", "EN": "Bolivia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 25, "DE": "Bosnien und Herzegowina", "EN": "Bosnia and Herzegovina" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 26, "DE": "Botswana", "EN": "Botswana" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 27, "DE": "Brasilien", "EN": "Brazil" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 28, "DE": "Brunei", "EN": "Brunei Darussalam" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 29, "DE": "Bulgarien", "EN": "Bulgaria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 30, "DE": "Burkina Faso", "EN": "Burkina Faso" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 31, "DE": "Burundi", "EN": "Burundi" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 32, "DE": "Chile", "EN": "Chile" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 33, "DE": "Taiwan", "EN": "Taiwan oder Republic of China" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 34, "DE": "China", "EN": "China" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 35, "DE": "Cookinseln", "EN": "Cook Islands" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 36, "DE": "Costa Rica", "EN": "Costa Rica" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 37, "DE": "Dänemark", "EN": "Denmark" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 38, "DE": "Deutschland", "EN": "Germany" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 39, "DE": "Dominica", "EN": "Dominica" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 40, "DE": "Dominikanische Republik", "EN": "Dominican Republic" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 41, "DE": "Dschibuti", "EN": "Djibouti" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 42, "DE": "Ecuador", "EN": "Ecuador" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 43, "DE": "El Salvador", "EN": "El Salvador" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 44, "DE": "Elfenbeinküste", "EN": "Ivory Coast" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 45, "DE": "Eritrea", "EN": "Eritrea" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 46, "DE": "Estland", "EN": "Estonia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 47, "DE": "Fidschi", "EN": "Fiji" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 48, "DE": "Finnland", "EN": "Finland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 49, "DE": "Frankreich", "EN": "France" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 50, "DE": "Gabun", "EN": "Gabon" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 51, "DE": "Gambia", "EN": "Gambia, the" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 52, "DE": "Georgien", "EN": "Georgia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 53, "DE": "Ghana", "EN": "Ghana" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 54, "DE": "Grenada", "EN": "Grenada" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 55, "DE": "Griechenland", "EN": "Greece" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 56, "DE": "Guatemala", "EN": "Guatemala" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 57, "DE": "Guinea", "EN": "Guinea" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 58, "DE": "Guinea-Bissau", "EN": "Guinea-Bissau" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 59, "DE": "Guyana", "EN": "Guyana" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 60, "DE": "Haiti", "EN": "Haiti" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 61, "DE": "Honduras", "EN": "Honduras" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 62, "DE": "Indien", "EN": "India" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 63, "DE": "Indonesien", "EN": "Indonesia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 64, "DE": "Irak", "EN": "Iraq" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 65, "DE": "Iran", "EN": "Iran" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 66, "DE": "Irland", "EN": "Ireland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 67, "DE": "Island", "EN": "Iceland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 68, "DE": "Israel", "EN": "Israel" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 69, "DE": "Italien", "EN": "Italy" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 70, "DE": "Jamaika", "EN": "Jamaica" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 71, "DE": "Japan", "EN": "Japan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 72, "DE": "Jemen", "EN": "Yemen" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 73, "DE": "Jordanien", "EN": "Jordan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 74, "DE": "Kambodscha", "EN": "Cambodia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 75, "DE": "Kamerun", "EN": "Cameroon" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 76, "DE": "Kanada", "EN": "Canada" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 77, "DE": "Kap Verde", "EN": "Cape Verde" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 78, "DE": "Kasachstan", "EN": "Kazakhstan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 79, "DE": "Katar", "EN": "Qatar" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 80, "DE": "Kenia", "EN": "Kenya" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 81, "DE": "Kirgisistan", "EN": "Kyrgyzstan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 82, "DE": "Kiribati", "EN": "Kiribati" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 83, "DE": "Kolumbien", "EN": "Colombia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 84, "DE": "Komoren", "EN": "Comoros" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 85, "DE": "Kongo, Demokratische Republik", "EN": "Congo, Democratic Republic of the (Kinshasa)" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 86, "DE": "Kongo, Republik", "EN": "Congo, Republic of (Brazzaville)" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 87, "DE": "Korea, Nord", "EN": "North Korea" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 88, "DE": "Korea, Süd", "EN": "Korea, Republic of (South Korea)" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 89, "DE": "Kosovo", "EN": "Kosovo" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 90, "DE": "Kroatien", "EN": "Croatia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 91, "DE": "Kuba", "EN": "Cuba" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 92, "DE": "Kuwait", "EN": "Kuwait" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 93, "DE": "Laos", "EN": "Lao, People’s Democratic Republic of" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 94, "DE": "Lesotho", "EN": "Lesotho" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 95, "DE": "Lettland", "EN": "Latvia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 96, "DE": "Libanon", "EN": "Lebanon" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 97, "DE": "Liberia", "EN": "Liberia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 98, "DE": "Libyen", "EN": "Libya" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 99, "DE": "Liechtenstein", "EN": "Liechtenstein" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 100, "DE": "Litauen", "EN": "Lithuania" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 101, "DE": "Luxemburg", "EN": "Luxembourg" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 102, "DE": "Madagaskar", "EN": "Madagascar" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 103, "DE": "Malawi", "EN": "Malawi" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 104, "DE": "Malaysia", "EN": "Malaysia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 105, "DE": "Malediven", "EN": "Maldives" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 106, "DE": "Mali", "EN": "Mali" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 107, "DE": "Malta", "EN": "Malta" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 108, "DE": "Marokko", "EN": "Morocco" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 109, "DE": "Marshallinseln", "EN": "Marshall Islands" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 110, "DE": "Mauretanien", "EN": "Mauritania" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 111, "DE": "Mauritius", "EN": "Mauritius" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 112, "DE": "Mazedonien", "EN": "Macedonia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 113, "DE": "Mexiko", "EN": "Mexico" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 114, "DE": "Mikronesien", "EN": "Micronesia, Federal States of" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 115, "DE": "Moldawien", "EN": "Moldova" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 116, "DE": "Monaco", "EN": "Monaco" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 117, "DE": "Mongolei", "EN": "Mongolia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 118, "DE": "Montenegro", "EN": "Montenegro" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 119, "DE": "Mosambik", "EN": "Mozambique" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 120, "DE": "Myanmar", "EN": "Myanmar oder Burma" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 121, "DE": "Namibia", "EN": "Namibia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 122, "DE": "Nauru", "EN": "Nauru" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 123, "DE": "Nepal", "EN": "Nepal" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 124, "DE": "Neuseeland", "EN": "New Zealand" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 125, "DE": "Nicaragua", "EN": "Nicaragua" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 126, "DE": "Niederlande", "EN": "Netherlands" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 127, "DE": "Niger", "EN": "Niger" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 128, "DE": "Nigeria", "EN": "Nigeria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 129, "DE": "Niue", "EN": "Niue" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 130, "DE": "Nordzypern", "EN": "Northern Cyprus" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 131, "DE": "Norwegen", "EN": "Norway" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 132, "DE": "Oman", "EN": "Oman" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 133, "DE": "Österreich", "EN": "Austria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 134, "DE": "Osttimor \/ Timor-Leste", "EN": "East Timor oder Timor-Leste" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 135, "DE": "Pakistan", "EN": "Pakistan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 136, "DE": "Palästina", "EN": "Palestine" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 137, "DE": "Palau", "EN": "Palau" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 138, "DE": "Panama", "EN": "Panama" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 139, "DE": "Papua-Neuguinea", "EN": "Papua New Guinea" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 140, "DE": "Paraguay", "EN": "Paraguay" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 141, "DE": "Peru", "EN": "Peru" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 142, "DE": "Philippinen", "EN": "Philippines" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 143, "DE": "Polen", "EN": "Poland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 144, "DE": "Portugal", "EN": "Portugal" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 145, "DE": "Ruanda", "EN": "Rwanda" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 146, "DE": "Rumänien", "EN": "Romania" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 147, "DE": "Russland", "EN": "Russia oder Russian Federation" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 148, "DE": "Salomonen", "EN": "Solomon Islands" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 149, "DE": "Sambia", "EN": "Zambia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 150, "DE": "Samoa", "EN": "Samoa" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 151, "DE": "San Marino", "EN": "San Marino" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 152, "DE": "São Tomé und Príncipe", "EN": "São Tomé and Príncipe" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 153, "DE": "Saudi-Arabien", "EN": "Saudi Arabia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 154, "DE": "Schweden", "EN": "Sweden" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 155, "DE": "Schweiz", "EN": "Switzerland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 156, "DE": "Senegal", "EN": "Senegal" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 157, "DE": "Serbien", "EN": "Serbia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 158, "DE": "Seychellen", "EN": "Seychelles" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 159, "DE": "Sierra Leone", "EN": "Sierra Leone" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 160, "DE": "Simbabwe", "EN": "Zimbabwe" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 161, "DE": "Singapur", "EN": "Singapore" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 162, "DE": "Slowakei", "EN": "Slovakia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 163, "DE": "Slowenien", "EN": "Slovenia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 164, "DE": "Somalia", "EN": "Somalia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 165, "DE": "Spanien", "EN": "Spain" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 166, "DE": "Sri Lanka", "EN": "Sri Lanka" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 167, "DE": "St. Kitts und Nevis", "EN": "Saint Kitts and Nevis" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 168, "DE": "St. Lucia", "EN": "Saint Lucia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 169, "DE": "St. Vincent und die Grenadinen", "EN": "Saint Vincent and the Grenadines" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 170, "DE": "Südafrika", "EN": "South Africa" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 171, "DE": "Sudan", "EN": "Sudan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 172, "DE": "Südossetien", "EN": "South Ossetia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 173, "DE": "Südsudan", "EN": "South Sudan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 174, "DE": "Suriname", "EN": "Suriname" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 175, "DE": "Swasiland", "EN": "Swaziland" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 176, "DE": "Syrien", "EN": "Syria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 177, "DE": "Tadschikistan", "EN": "Tajikistan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 178, "DE": "Tansania", "EN": "Tanzania" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 179, "DE": "Thailand", "EN": "Thailand" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 180, "DE": "Togo", "EN": "Togo" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 181, "DE": "Tonga", "EN": "Tonga" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 182, "DE": "Transnistrien", "EN": "Transnistria" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 183, "DE": "Trinidad und Tobago", "EN": "Trinidad and Tobago" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 184, "DE": "Tschad", "EN": "Chad" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 185, "DE": "Tschechien", "EN": "Czech Republic" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 186, "DE": "Tunesien", "EN": "Tunisia" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 187, "DE": "Türkei", "EN": "Turkey" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 188, "DE": "Turkmenistan", "EN": "Turkmenistan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 189, "DE": "Tuvalu", "EN": "Tuvalu" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 190, "DE": "Uganda", "EN": "Uganda" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 191, "DE": "Ukraine", "EN": "Ukraine" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 192, "DE": "Ungarn", "EN": "Hungary" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 193, "DE": "Uruguay", "EN": "Uruguay" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 194, "DE": "Usbekistan", "EN": "Uzbekistan" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 195, "DE": "Vanuatu", "EN": "Vanuatu" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 196, "DE": "Vatikanstadt", "EN": "Vatican City" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 197, "DE": "Venezuela", "EN": "Venezuela" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 198, "DE": "Vereinigte Arabische Emirate", "EN": "United Arab Emirates" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 199, "DE": "Vereinigte Staaten", "EN": "United States" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 200, "DE": "Vereinigtes Königreich", "EN": "United Kingdom" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 201, "DE": "Vietnam", "EN": "Vietnam" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 202, "DE": "Weißrussland", "EN": "Belarus" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 203, "DE": "Westsahara", "EN": "Western Sahara" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 204, "DE": "Zentralafrikanische Republik", "EN": "Central African Republic" }, "geometry": null },
        { "type": "Feature", "properties": { "SNo": 205, "DE": "Zypern", "EN": "Cyprus" }, "geometry": null }
    ];
  };
}
